/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlAbonos;
import Control.ControlFactura;
import Control.ControlPersona;
import java.awt.HeadlessException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CarolVasquez
 */
public class GUIAbonos extends javax.swing.JFrame {

    Object datosCliente[][] = null;
    Object datosFactura[][] = null;
    DefaultTableModel dtm;
    String nombresColumnas[] = {"Codigo Factura", "Valor de Venta", "Fecha de Venta", "Vendedor", "Abonos"};
    /**
     * Creates new form GUIAbonos
     */
    public GUIAbonos() {
        dtm = new DefaultTableModel(datosFactura, nombresColumnas);        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacturas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtAbono = new javax.swing.JTextField();
        btnAbono = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtFactDocCliente = new javax.swing.JTextField();
        txtFactNomCliente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFactApeCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(570, 350));
        setMinimumSize(new java.awt.Dimension(570, 350));

        jPanel1.setBackground(new java.awt.Color(250, 246, 246));
        jPanel1.setMaximumSize(new java.awt.Dimension(780, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(780, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(780, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblFacturas.setModel(dtm);
        jScrollPane1.setViewportView(tblFacturas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 760, 100));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("Abono:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));
        jPanel1.add(txtAbono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 96, -1));

        btnAbono.setBackground(new java.awt.Color(204, 204, 204));
        btnAbono.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnAbono.setForeground(new java.awt.Color(51, 0, 102));
        btnAbono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/abonar.png"))); // NOI18N
        btnAbono.setText("Realizar Abono");
        btnAbono.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbonoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAbono, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, 40));

        jLabel4.setBackground(new java.awt.Color(51, 0, 51));
        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Facturas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 670, 10));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel8.setText("Número Documento:*");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtFactDocCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFactDocClienteKeyReleased(evt);
            }
        });
        jPanel1.add(txtFactDocCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 150, -1));
        jPanel1.add(txtFactNomCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 200, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel9.setText("Nombre:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel3.setText("Apellido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 100, -1));
        jPanel1.add(txtFactApeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 190, -1));

        btnBuscarCliente.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscarCliente.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnBuscarCliente.setForeground(new java.awt.Color(51, 0, 102));
        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/buscar.png"))); // NOI18N
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnBuscarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 120, 40));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 20, 60));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 730, 10));

        jSeparator5.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 20, 60));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Consultar Facturas /Abonos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 18, 540, 40));

        btnVolver.setBackground(new java.awt.Color(204, 204, 204));
        btnVolver.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atras.png"))); // NOI18N
        btnVolver.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 60, 40));

        jLabel6.setBackground(new java.awt.Color(51, 0, 51));
        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Cliente");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        ControlPersona cp = new ControlPersona();
        ControlFactura cf = new ControlFactura();
        if(txtFactDocCliente.getText().length()>0 || txtFactNomCliente.getText().length()>0 || txtFactApeCliente.getText().length()>0){
            if(txtFactDocCliente.getText().length()>0 && txtFactNomCliente.getText().length()>0 && txtFactApeCliente.getText().length()>0){
                datosCliente = cp.consultarPersonaTodos(Integer.parseInt(txtFactDocCliente.getText()),
                    txtFactNomCliente.getText(), txtFactApeCliente.getText());
            }else{
                if(txtFactDocCliente.getText().length()==0 && txtFactNomCliente.getText().length()>0 && txtFactApeCliente.getText().length()==0){
                    datosCliente = cp.consultarPersonaNombres(txtFactNomCliente.getText());
                }else{
                    if(txtFactDocCliente.getText().length()>0 && txtFactNomCliente.getText().length()==0 && txtFactApeCliente.getText().length()==0){
                        datosCliente = cp.consultarPersonaDocumento(Integer.parseInt(txtFactDocCliente.getText()));
                    }else{
                        if(txtFactDocCliente.getText().length()>0 && txtFactNomCliente.getText().length()>0 && txtFactApeCliente.getText().length()==0){
                            datosCliente = cp.consultarPersonaDocNombres(Integer.parseInt(txtFactDocCliente.getText()), txtFactNomCliente.getText());
                        }
                    }
                }
            }
            if(datosCliente[0][0]==null){
                JOptionPane.showMessageDialog(this, "El cliente no existe");
                txtFactDocCliente.setText("");
                txtFactNomCliente.setText("");
                txtFactApeCliente.setText("");
            }else{
                txtFactDocCliente.setText(String.valueOf(datosCliente[0][1]));
                txtFactNomCliente.setText((String) datosCliente[0][2]);
                txtFactApeCliente.setText((String) datosCliente[0][3]);
                datosFactura = cf.consultarFacturaAbonos(Integer.parseInt(String.valueOf(datosCliente[0][0])));
                dtm = new DefaultTableModel(datosFactura, nombresColumnas);
                tblFacturas.setModel(dtm);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Ingrese un parámetro de búsqueda");
        }

    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        GUIPrincipal gpr = new GUIPrincipal();
        this.setVisible(false);
        gpr.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtFactDocClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFactDocClienteKeyReleased
        txtFactNomCliente.setText("");
        txtFactApeCliente.setText("");
        datosFactura = null;
        dtm = new DefaultTableModel(datosFactura, nombresColumnas);
        tblFacturas.setModel(dtm);
    }//GEN-LAST:event_txtFactDocClienteKeyReleased

    private void btnAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbonoActionPerformed
        try{
            if(txtAbono.getText().length()>0){
                ControlAbonos ca = new ControlAbonos();
                int filaseleccionada;
                int codAbono;
                float abonosRealizados;
                Object datos[][] = ca.consultarCodMaxAbonos();

                if(datos[0][0]!=null){
                    codAbono = Integer.parseInt(String.valueOf(datos[0][0]))+1;
                }else{
                    codAbono = 1;
                }

                DefaultTableModel modelotabla=(DefaultTableModel) tblFacturas.getModel();
                try{
                    filaseleccionada= tblFacturas.getSelectedRow();
                    if (filaseleccionada==-1 || modelotabla.getValueAt(filaseleccionada, 0)==null){
                        JOptionPane.showMessageDialog(this, "Debe Seleccionar una Factura");
                    }else{
                        int codFactura = Integer.parseInt(String.valueOf(modelotabla.getValueAt(filaseleccionada, 0)));
                        float valorFactura = Float.parseFloat(String.valueOf(modelotabla.getValueAt(filaseleccionada, 1)));
                        try{
                            abonosRealizados = Float.parseFloat(String.valueOf(modelotabla.getValueAt(filaseleccionada, 4)));                       
                        }catch(NumberFormatException FE){
                            abonosRealizados=0;
                        }

                        float valorAbono = Float.parseFloat(txtAbono.getText());

                        if(valorAbono+abonosRealizados <= valorFactura){
                            int res = JOptionPane.showConfirmDialog(this, "Está seguro que desea realizar el abono por valor de: " + txtAbono.getText(), "Advertencia", JOptionPane.INFORMATION_MESSAGE);
                            if(res==JOptionPane.YES_OPTION){
                                ca.insertarAbono(codAbono, valorAbono, codFactura);
                                JOptionPane.showMessageDialog(this, "Se ha realizado el abono exitosamente");
                                txtFactNomCliente.setText("");
                                txtFactApeCliente.setText("");
                                datosFactura = null;
                                dtm = new DefaultTableModel(datosFactura, nombresColumnas);
                                tblFacturas.setModel(dtm); 
                                Object datosCliente[][] = null;
                                Object datosFactura[][] = null;
                            }else{
                                txtFactNomCliente.setText("");
                                txtFactApeCliente.setText("");
                                datosFactura = null;
                                dtm = new DefaultTableModel(datosFactura, nombresColumnas);
                                tblFacturas.setModel(dtm);  
                                Object datosCliente[][] = null;
                                Object datosFactura[][] = null;
                            }                       
                        }else{
                            JOptionPane.showMessageDialog(this, "Ha excedido el valor de la compra");
                        }                   
                     }
                }catch (HeadlessException ex){
                      JOptionPane.showMessageDialog(null, "Error: "+ex+"\nInténtelo nuevamente", " .::Error En la Operacion::." ,JOptionPane.ERROR_MESSAGE);
                }                        
            }else{
                JOptionPane.showMessageDialog(this, "Debe elegir una factura y diligenciar el valor del abono");
            }            
        }catch(NumberFormatException EX){
            JOptionPane.showMessageDialog(this, "Ingrese un cliente");
        }
    }//GEN-LAST:event_btnAbonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAbonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAbonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAbonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAbonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAbonos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbono;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable tblFacturas;
    private javax.swing.JTextField txtAbono;
    private javax.swing.JTextField txtFactApeCliente;
    private javax.swing.JTextField txtFactDocCliente;
    private javax.swing.JTextField txtFactNomCliente;
    // End of variables declaration//GEN-END:variables
}
