/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlEmpleado;
import Control.ControlRoles;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CarolVasquez
 */
public class GUIDesbloqueoEmpleados extends javax.swing.JFrame {

    DefaultTableModel dtm;
    Object[][] data = null;
    Object[][] userSeleccionado = new Object[1][2];
    ControlEmpleado ce = new ControlEmpleado();
    String nombresColumnas[] = {"Codigo Empleado", "Nombre de Usuario"};
    /**
     * Creates new form GUIDesbloqueoEmpleados
     */
    public GUIDesbloqueoEmpleados() {
        data = ce.consultarEmpleadoBloqueado();
        dtm = new DefaultTableModel(data, nombresColumnas);  
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void actualizarTabla() {
        dtm = new DefaultTableModel(data, nombresColumnas);
        tblBloqueados.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnDesbloquear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBloqueados = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 246, 246));
        jPanel1.setMaximumSize(new java.awt.Dimension(570, 350));
        jPanel1.setMinimumSize(new java.awt.Dimension(570, 350));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Desbloqueo de Acceso Empleados");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 390, 30));

        btnVolver.setBackground(new java.awt.Color(204, 204, 204));
        btnVolver.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atras.png"))); // NOI18N
        btnVolver.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 40));

        btnDesbloquear.setBackground(new java.awt.Color(204, 204, 204));
        btnDesbloquear.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnDesbloquear.setForeground(new java.awt.Color(51, 0, 102));
        btnDesbloquear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/desbloquear.png"))); // NOI18N
        btnDesbloquear.setText("Desbloquear");
        btnDesbloquear.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnDesbloquear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDesbloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesbloquearActionPerformed(evt);
            }
        });
        jPanel1.add(btnDesbloquear, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 170, 40));

        tblBloqueados.setModel(dtm);
        tblBloqueados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblBloqueadosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblBloqueados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 510, 120));

        jLabel4.setBackground(new java.awt.Color(51, 0, 51));
        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Empleados Bloqueados");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        GUIPrincipal gpr = new GUIPrincipal();
        this.setVisible(false);
        gpr.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnDesbloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesbloquearActionPerformed
        if(userSeleccionado[0][0]!=null){
            ce.DesbloquearUsuario(Integer.parseInt(String.valueOf(userSeleccionado[0][0])), "F");
            ce.eliminarHistorial(Integer.parseInt(String.valueOf(userSeleccionado[0][0])));
            userSeleccionado = null;
            this.actualizarTabla();
            JOptionPane.showMessageDialog(this, "Usuario desbloqueado exitosamente!!");            
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario");
        }
    }//GEN-LAST:event_btnDesbloquearActionPerformed

    private void tblBloqueadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBloqueadosMousePressed
        int filaseleccionada;
        DefaultTableModel modelotabla=(DefaultTableModel) tblBloqueados.getModel();
        try{
            filaseleccionada= tblBloqueados.getSelectedRow();
            if (filaseleccionada==-1 || modelotabla.getValueAt(filaseleccionada, 0)==null){
                JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario");
            }else{
                userSeleccionado[0][0] = Integer.parseInt((String.valueOf(modelotabla.getValueAt(filaseleccionada, 0))));
                userSeleccionado[0][1] = (String.valueOf(modelotabla.getValueAt(filaseleccionada, 1)));
            }
        }catch (HeadlessException ex){
            JOptionPane.showMessageDialog(null, "Error: "+ex+"\nInténtelo nuevamente", " .::Error En la Operacion::." ,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblBloqueadosMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIDesbloqueoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIDesbloqueoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIDesbloqueoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIDesbloqueoEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIDesbloqueoEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesbloquear;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBloqueados;
    // End of variables declaration//GEN-END:variables
}
