/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlRoles;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CarolVasquez
 */
public class GUIRoles extends javax.swing.JFrame {

    DefaultTableModel dtm;
    Object[][] data = null;
    ControlRoles cr = new ControlRoles();
    String nombresColumnas[] = {"Codigo Rol", "Nombre Rol"};
    
    public GUIRoles() {
        data = cr.consultarRol();
        dtm = new DefaultTableModel(data, nombresColumnas);  
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void actualizarTabla() {
        dtm = new DefaultTableModel(data, nombresColumnas);
        tblRoles.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarRol1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodRol = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        txtNomRol = new javax.swing.JTextField();
        btnActualRol = new javax.swing.JButton();
        btnGuardRol = new javax.swing.JButton();
        btnElimRol = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRoles = new javax.swing.JTable();
        btnBuscRol = new javax.swing.JButton();

        btnBuscarRol1.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscarRol1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnBuscarRol1.setForeground(new java.awt.Color(51, 0, 102));
        btnBuscarRol1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/buscar.png"))); // NOI18N
        btnBuscarRol1.setText("Buscar");
        btnBuscarRol1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnBuscarRol1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscarRol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRol1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 246, 246));
        jPanel1.setMaximumSize(new java.awt.Dimension(570, 350));
        jPanel1.setMinimumSize(new java.awt.Dimension(570, 350));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Administrador de Roles");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 270, 20));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Codigo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, 20));

        txtCodRol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodRolKeyReleased(evt);
            }
        });
        jPanel1.add(txtCodRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 80, -1));

        btnVolver.setBackground(new java.awt.Color(204, 204, 204));
        btnVolver.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/atras.png"))); // NOI18N
        btnVolver.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 40));
        jPanel1.add(txtNomRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 160, -1));

        btnActualRol.setBackground(new java.awt.Color(204, 204, 204));
        btnActualRol.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnActualRol.setForeground(new java.awt.Color(51, 0, 102));
        btnActualRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/actualizar.png"))); // NOI18N
        btnActualRol.setText("Actualizar");
        btnActualRol.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnActualRol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualRolActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 150, 40));

        btnGuardRol.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardRol.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnGuardRol.setForeground(new java.awt.Color(51, 0, 102));
        btnGuardRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/guardar.png"))); // NOI18N
        btnGuardRol.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnGuardRol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardRolActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 40, 40));

        btnElimRol.setBackground(new java.awt.Color(204, 204, 204));
        btnElimRol.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnElimRol.setForeground(new java.awt.Color(51, 0, 102));
        btnElimRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/eliminar.png"))); // NOI18N
        btnElimRol.setText("Eliminar");
        btnElimRol.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnElimRol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnElimRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimRolActionPerformed(evt);
            }
        });
        jPanel1.add(btnElimRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 140, 40));

        tblRoles.setModel(dtm);
        tblRoles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblRolesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblRoles);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 510, 120));

        btnBuscRol.setBackground(new java.awt.Color(204, 204, 204));
        btnBuscRol.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnBuscRol.setForeground(new java.awt.Color(51, 0, 102));
        btnBuscRol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/buscar.png"))); // NOI18N
        btnBuscRol.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnBuscRol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscRolActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        GUIPrincipal gpr = new GUIPrincipal();
        this.setVisible(false);
        gpr.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnActualRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualRolActionPerformed
        if(txtCodRol.getText().length()>0 && txtNomRol.getText().length()>0){
            if(cr.actualizarRol(Integer.parseInt(txtCodRol.getText()), txtNomRol.getText())){
                JOptionPane.showMessageDialog(this, "Rol actualizado satisfactoriamente");
                data = cr.consultarRol();
                this.actualizarTabla();
            }else{
                JOptionPane.showMessageDialog(this, "Revise la información diligenciada");
            }            
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un rol");
        }
    }//GEN-LAST:event_btnActualRolActionPerformed

    private void btnGuardRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardRolActionPerformed
        if(txtCodRol.getText().length()>0 && txtNomRol.getText().length()>0){
            if(cr.insertarRol(Integer.parseInt(txtCodRol.getText()), txtNomRol.getText())){
                JOptionPane.showMessageDialog(this, "Rol creado satisfactoriamente");
                data = cr.consultarRol();
                this.actualizarTabla();
            }else{
                JOptionPane.showMessageDialog(this, "El código del Rol ya existe");
                txtCodRol.enable(true);
                data = cr.consultarRol();
                this.actualizarTabla();                
                txtCodRol.setText("");
                txtNomRol.setText("");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debe ingresar todos los campos obligatorios");
        }
    }//GEN-LAST:event_btnGuardRolActionPerformed

    private void btnBuscarRol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRol1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarRol1ActionPerformed

    private void btnElimRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimRolActionPerformed
        if(txtCodRol.getText().length()>0 && txtNomRol.getText().length()>0){
            if(cr.eliminarRol(Integer.parseInt(txtCodRol.getText()))){
                JOptionPane.showMessageDialog(this, "Rol eliminado");
                data = cr.consultarRol();
                this.actualizarTabla();
            }else{
                JOptionPane.showMessageDialog(this, "Revise la información diligenciada");
            }            
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un rol");
        }        
    }//GEN-LAST:event_btnElimRolActionPerformed

    private void btnBuscRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscRolActionPerformed
        txtCodRol.enable(true);
        ControlRoles cr = new ControlRoles();
       if(txtCodRol.getText().length()>0 || txtNomRol.getText().length()>0){
            if(txtCodRol.getText().length()>0 && txtNomRol.getText().length()>0){
                data = cr.consultarRolTodos(Integer.parseInt(txtCodRol.getText()), txtNomRol.getText());
                this.actualizarTabla();
            }else{
                if(txtCodRol.getText().length()>0 && txtNomRol.getText().length()==0){
                    data = cr.consultarRol(Integer.parseInt(txtCodRol.getText()));
                 }else{
                    if(txtCodRol.getText().length()==0 && txtNomRol.getText().length()>0){
                        data = cr.consultarRolNombre(txtNomRol.getText());
                    }
                }     
            }           
       }else{
           JOptionPane.showMessageDialog(this, "Ingrese un cliente");
       }
       
         if(data[0][0]==null){
             JOptionPane.showMessageDialog(this, "El Rol no Existe");
                txtNomRol.setText("");
                txtCodRol.setText("");              
         }else{
             txtCodRol.setText(String.valueOf(data[0][0]));
             txtNomRol.setText((String) data[0][1]);
             this.actualizarTabla();
         } 
       
    }//GEN-LAST:event_btnBuscRolActionPerformed

    private void txtCodRolKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodRolKeyReleased
        txtNomRol.setText("");
        data = cr.consultarRol();
        txtCodRol.enable(true);
        this.actualizarTabla();
    }//GEN-LAST:event_txtCodRolKeyReleased

    private void tblRolesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRolesMousePressed
        int filaseleccionada;
        DefaultTableModel modelotabla=(DefaultTableModel) tblRoles.getModel();
           try{
                filaseleccionada= tblRoles.getSelectedRow();
                if (filaseleccionada==-1 || modelotabla.getValueAt(filaseleccionada, 0)==null){
                    JOptionPane.showMessageDialog(null, "Elija un Rol");
                }else{
                    txtCodRol.setText(String.valueOf(modelotabla.getValueAt(filaseleccionada, 0)));
                    txtCodRol.enable(false);
                    txtNomRol.setText((String) modelotabla.getValueAt(filaseleccionada, 1));   
                 }
              }catch (HeadlessException ex){
                    JOptionPane.showMessageDialog(null, "Error: "+ex+"\nInténtelo nuevamente", " .::Error En la Operacion::." ,JOptionPane.ERROR_MESSAGE);
              }        
    }//GEN-LAST:event_tblRolesMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRoles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRoles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualRol;
    private javax.swing.JButton btnBuscRol;
    private javax.swing.JButton btnBuscarRol1;
    private javax.swing.JButton btnElimRol;
    private javax.swing.JButton btnGuardRol;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRoles;
    private javax.swing.JTextField txtCodRol;
    private javax.swing.JTextField txtNomRol;
    // End of variables declaration//GEN-END:variables
}
